### ISSUE TITLE
why you donnot use xray mask

### ISSUE THREAD

**Issue by zb-zuishuai** [yakamoz5/Uni#1]
In that paper,they put xray mask into model ,I find you donnot use it ,only put the blend images into model .
I think  only use the blend images ,it works as the common way . 
Mask is the core of that paper ,you delete it ,the result of your paper maybe not right

**Comment by yakamoz5** [comment]
In their experiments, they compare different state of the art neural networks in terms of detection performance.
Whilst their detection network uses the xRay masks, the others do not. A part of their idea is that other networks can also be trained with the data generation method they propose - and they claim that other networks thereby are capable of learning similar (or even the same) structure as the explicit x-Ray method does.

So I guess we did not do anything wrong regarding testing their assumption and not being able to prove it in our cases - as we put it.
Of course, it can be that we have other mistakes and could have varied our source data etc.
But regarding your argument: there is nothing wrong. The Xray research team also has not used the face X-rays with other networks (since they are not designed to use them). But they explicitly stated, that they think that the other networks have learnt the face X-rays implicitly. I can later cite from their paper if you want to.

**Comment by yakamoz5** [comment]
Update: this is also only our intermediate finding. This is part of a university course that was strictly limited in time. But given out settings we could not prove the findings. This may have several reasons and further work needs to be certainly done.
